version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: java
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/java
      DB_USER: root
      DB_PASSWORD: 
volumes:
      - ./scripts:/docker-entrypoint-initdb.d